// Generated by gencpp from file inverse_kinematics/inverse_kinematics_coordinate_msg.msg
// DO NOT EDIT!


#ifndef INVERSE_KINEMATICS_MESSAGE_INVERSE_KINEMATICS_COORDINATE_MSG_H
#define INVERSE_KINEMATICS_MESSAGE_INVERSE_KINEMATICS_COORDINATE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inverse_kinematics
{
template <class ContainerAllocator>
struct inverse_kinematics_coordinate_msg_
{
  typedef inverse_kinematics_coordinate_msg_<ContainerAllocator> Type;

  inverse_kinematics_coordinate_msg_()
    : X_length(0.0)
    , Y_length(0.0)
    , YAW_length(0.0)  {
    }
  inverse_kinematics_coordinate_msg_(const ContainerAllocator& _alloc)
    : X_length(0.0)
    , Y_length(0.0)
    , YAW_length(0.0)  {
  (void)_alloc;
    }



   typedef double _X_length_type;
  _X_length_type X_length;

   typedef double _Y_length_type;
  _Y_length_type Y_length;

   typedef double _YAW_length_type;
  _YAW_length_type YAW_length;




  typedef boost::shared_ptr< ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> const> ConstPtr;

}; // struct inverse_kinematics_coordinate_msg_

typedef ::inverse_kinematics::inverse_kinematics_coordinate_msg_<std::allocator<void> > inverse_kinematics_coordinate_msg;

typedef boost::shared_ptr< ::inverse_kinematics::inverse_kinematics_coordinate_msg > inverse_kinematics_coordinate_msgPtr;
typedef boost::shared_ptr< ::inverse_kinematics::inverse_kinematics_coordinate_msg const> inverse_kinematics_coordinate_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inverse_kinematics

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'inverse_kinematics': ['/home/odroid/catkin_ws/src/inverse_kinematics/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d3eb76a6bd82299f845783a52ac0cab";
  }

  static const char* value(const ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d3eb76a6bd82299ULL;
  static const uint64_t static_value2 = 0xf845783a52ac0cabULL;
};

template<class ContainerAllocator>
struct DataType< ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inverse_kinematics/inverse_kinematics_coordinate_msg";
  }

  static const char* value(const ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 X_length\n\
float64 Y_length\n\
float64 YAW_length\n\
";
  }

  static const char* value(const ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X_length);
      stream.next(m.Y_length);
      stream.next(m.YAW_length);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct inverse_kinematics_coordinate_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inverse_kinematics::inverse_kinematics_coordinate_msg_<ContainerAllocator>& v)
  {
    s << indent << "X_length: ";
    Printer<double>::stream(s, indent + "  ", v.X_length);
    s << indent << "Y_length: ";
    Printer<double>::stream(s, indent + "  ", v.Y_length);
    s << indent << "YAW_length: ";
    Printer<double>::stream(s, indent + "  ", v.YAW_length);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INVERSE_KINEMATICS_MESSAGE_INVERSE_KINEMATICS_COORDINATE_MSG_H
